image: python:3.8

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - static analysis
  - test
  - deploy

before_script:
  - python3.8 -m pip install virtualenv
  - python3.8 -m virtualenv venv
  - source venv/bin/activate
  - python3.8 -m pip install -r requirements.txt

flake8:
  stage: static analysis
  script:
    - flake8 --filename *.py
  tags:
    - docker

test:
  stage: test
  script:
    - pip install --editable .
    - pytest --cov=filter --cov=extract --cov=export --cov=corpus --cov-branch tests -vv
  tags:
    - docker

pages:
  stage: deploy
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd docs
    - make html
    - mv build/html ../public/
  tags:
    - shell
  artifacts:
    paths:
      - public