image: python:3.8

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - static analysis
  - test

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - export PYTHONPATH=

flake8:
  stage: static analysis
  script:
    - flake8 --filename *.py
  tags:
    - docker

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install --editable .
    - pytest --cov=filter --cov=extract --cov-branch --cov-report=html tests
  tags:
    - docker
