image: python:3.8

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - static analysis
  - test
  - deploy

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

flake8:
  stage: static analysis
  script:
    - flake8 --filename *.py
  tags:
    - docker

test:
  stage: test
  script:
    - pip install --editable .
    - pytest --cov=filter --cov=extract --cov-branch --cov-report=html tests
  tags:
    - docker

pages:
  stage: deploy
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd docs
    - make html
    - mv build/html ../../public/
  artifacts:
    paths:
      - public